# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       extra-cmake-modules

# >> macros
# << macros

Summary:    KDE extra cmake modules
Version:    0.0.11.20140323.f686ff7
Release:    1
Group:      Applications/System
License:    BSD
URL:        http://www.kde.org
Source0:    %{name}-%{version}.tar.xz
Source100:  extra-cmake-modules.yaml
Requires:   cmake
BuildRequires:  cmake
BuildRequires:  python

%description
Extra modules for KDE Frameworks

%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
# << build pre

%cmake .  \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_datadir}/ECM/modules/ECMVersionHeader.h.in
%{_datadir}/ECM/modules/*.cmake
%{_datadir}/ECM/kde-modules/*.cmake
%{_datadir}/ECM/find-modules/*.cmake
%{_datadir}/ECM/cmake/*.cmake
# >> files
# << files
