# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       kde-extra-cmake-modules

# >> macros
# << macros

Summary:    KDE extra cmake modules
Version:    0.0.9.20131217.83f4d25
Release:    1
Group:      Applications/System
License:    BSD
Source0:    kde-extra-cmake-modules-%{version}.tar.bz2
Source100:  kde-extra-cmake-modules.yaml
BuildRequires:  cmake >= 2.8.12
BuildRequires:  python

%description
Extra modules for building kde solid


%prep
%setup -q -n %{name}


# >> setup
# << setup

%build
# >> build pre
# << build pre
%ifnarch %{ix86} x86_64
# HACK!!! Please remove when possible.
# cmake is accelerated but version is too old
mkdir /tmp/bin
cp -a /usr/bin/cmake /usr/share/cmake/Modules /usr/share/cmake/Templates /tmp/bin/
PATH=/tmp/bin:$PATH
/tmp/bin/cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DCMAKE_SKIP_RPATH:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON . -DCMAKE_BUILD_TYPE=RelWithDebInfo
%else

%cmake .  \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo
%endif

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post


%files
%defattr(-,root,root,-)
%{_datadir}/ECM/modules/ECMVersionHeader.h.in
%{_datadir}/ECM/modules/*.cmake
%{_datadir}/ECM/kde-modules/*.cmake
%{_datadir}/ECM/find-modules/*.cmake
%{_datadir}/ECM/cmake/*.cmake
# >> files
# << files
